apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: azooinmyluggagewebapp 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: azooinmyluggagewebapp 
    spec:
      containers:
        - name: azooinmyluggagewebapp 
          image: builddemo.azurecr.io/azooinmyluggagewebapp 
          ports:
          - containerPort: 3000